<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <PlatformTarget>AnyCPU</PlatformTarget>
      <Prefer32bit>false</Prefer32bit>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DSharpPlus" Version="4.4.6" />
      <PackageReference Include="DSharpPlus.SlashCommands" Version="4.4.6" />
      <PackageReference Include="Serilog" Version="3.1.1" />
      <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Database\Database.csproj" />
      <ProjectReference Include="..\Tools\Tools.csproj" />
    </ItemGroup>

</Project>
